
package crud2;

import Conexion.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProductosAlmacen extends javax.swing.JFrame {
    DefaultTableModel modelo;

    public ProductosAlmacen() {
        initComponents();
        this.setLocationRelativeTo(null);


        String[] titulos = {"ID","Nombre","Marca","Categoria","Precio","Cantidad Disponible"};
        modelo = new DefaultTableModel(null,titulos);
        datos.setModel(modelo);
        //Cargando los datos en mi tabla para que puedan ser mostrados al usuario.
        this.consultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        datoss = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        jLabel2.setText("PRODUCTOS DE ALMACEN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kelvy\\OneDrive\\Escritorio\\Mis programas\\city.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 0, 200, 490));

        jLabel5.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        jLabel5.setText("Nombre ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));
        jPanel1.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        jLabel4.setText("Categoria");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));
        jPanel1.add(txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 160, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        jLabel6.setText("Precio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Bk", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad Disponible");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));
        jPanel1.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 160, -1));

        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Categoria", "Precio", "Cantidad Disponible"
            }
        ));
        datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datosMouseClicked(evt);
            }
        });
        datoss.setViewportView(datos);

        jPanel1.add(datoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 670, 250));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        jButton1.setText("Cerrar sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 150, 30));

        actualizar.setBackground(new java.awt.Color(153, 153, 153));
        actualizar.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 120, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 90, 30));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 90, 30));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Roboto Bk", 1, 18)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datosMouseClicked
        int fila = datos.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"Producto no seleccionado");

        }else{
            String nombre = (String)datos.getValueAt(fila,1);
            String marca = (String)datos.getValueAt(fila,2);
            String categoria = (String)datos.getValueAt(fila,3);
            String precio = (String)datos.getValueAt(fila,4);
            String cantidad = (String)datos.getValueAt(fila,5);

            txtnombre.setText(nombre);
            txtmarca.setText(marca);
            txtcategoria.setText(categoria);
            txtprecio.setText(precio);
            txtcantidad.setText(cantidad);
        }
    }//GEN-LAST:event_datosMouseClicked

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
          modificar();
    }//GEN-LAST:event_actualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          login a = new login();
          a.setVisible(true);
          this.setVisible(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

          ProductosUsuarios a = new ProductosUsuarios();
          a.setVisible(true);
          this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Agregar a = new Agregar();
         a.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosAlmacen().setVisible(true);
            }
        });
    }
    
    void consultar(){
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
            
        
        //Estableciendo conexión en mi base de datos.
        conexion objConexion= new conexion();
        //Try catch para el manejo de posibles errores.
          try {
            //Realizando consulta para traer todos los registros que esten en mi tabla usuario de mi base de datos sistema.
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM productos");
            //Tomando todos los registros y guardandolo en un object para luego mostarlos en mi tabla del programa...
            while (resultado.next()) {
                System.out.println(resultado.getString("id"));
                System.out.println(resultado.getString("nombre"));
                System.out.println(resultado.getString("marca"));
                System.out.println(resultado.getString("categoria"));
                System.out.println(resultado.getString("precio"));
                System.out.println(resultado.getString("cantidad_disponible"));
                Object[] Producto={resultado.getString("id"),resultado.getString("nombre"),resultado.getString("marca"),resultado.getString("categoria"),resultado.getString("precio"),resultado.getString("cantidad_disponible")};
                modelo.addRow(Producto);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    void modificar(){
           
        String nombre = txtnombre.getText();
        String marca = txtmarca.getText();
        String categoria = txtcategoria.getText();
        String precio = txtprecio.getText();
        String cantidad = txtcantidad.getText();
        conexion objConexion= new conexion();
        //Recuperando los datos.

        int fila = datos.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"Usuario no seleccionado");
        
        }else{
            int id = Integer.parseInt((String)datos.getValueAt(fila,0).toString());

        //Estableciendo mi sentencia DELETE para poder borrar los registros que contenga mi tabla usuario.
        String strSentenciaInsert= String.format("update productos set nombre ='"+nombre+"',marca='"+marca+"',categoria='"+categoria+"',precio='"+precio+"',cantidad_disponible='"+cantidad+"' WHERE id = '"+id+"'");
        //Ejecutando sentencia...
        objConexion.ejecutarSentenciaMYSQL(strSentenciaInsert);
        //Actualizando tabla para que cargue nuevamente los registros.
        this.consultar();
        //Limpiando mis txtFields.
        this.nuevo();
        }
    }
    
    void nuevo(){

        txtnombre.setText("");
        txtmarca.setText("");
        txtcategoria.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
    }
    
    void eliminar(){
        
//Estableciendo conexión con mi Base De Datos sistema.
        conexion objConexion= new conexion();
        //Recuperando los datos.

        int fila = datos.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null,"Producto no seleccionado");

        }else{
            int id = Integer.parseInt((String)datos.getValueAt(fila,0).toString());

        //Estableciendo mi sentencia DELETE para poder borrar los registros que contenga mi tabla usuario.
        String strSentenciaInsert= String.format("DELETE FROM productos WHERE id = %d",id);
        //Ejecutando sentencia...
        objConexion.ejecutarSentenciaMYSQL(strSentenciaInsert);
        JOptionPane.showMessageDialog(null,"Producto eliminado exitosamente");
        //Actualizando tabla para que cargue nuevamente los registros.
        this.consultar();
        this.nuevo();
        }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTable datos;
    private javax.swing.JScrollPane datoss;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
